### ISSUE TITLE
モデルのテストの作成

### ISSUE THREAD

**Issue by yh2020** [CircleAround/eventure#89]
現在までに3つのモデルを作成しており、event.rbとticket.rb内のメソッドについてテストを行う。
- event.rb
  - created_by?
  - start_time_should_be_before_end_time
- user.rb
  - check_all_events_finished
1. [x] created_by?のテスト #90 
2. [x] start_time_should_be_before_end_timeのテスト #91 
3. [ ] check_all_events_finishedのテスト #92
